// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArG4Tbfewqs9ZA0GsrvA6zTAxkaZnsyCk',
    appId: '1:41303225217:web:4d724184e4366fb36cee80',
    messagingSenderId: '41303225217',
    projectId: 'mylez-opacity-app',
    authDomain: 'mylez-opacity-app.firebaseapp.com',
    storageBucket: 'mylez-opacity-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtq-pMmG50hKVtiEjpf2ZtPHv7_vRlWPI',
    appId: '1:41303225217:android:3e3a05067db20fd66cee80',
    messagingSenderId: '41303225217',
    projectId: 'mylez-opacity-app',
    storageBucket: 'mylez-opacity-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHiXkmwahk75GuRDyezUUDbG_HkuzzgfU',
    appId: '1:41303225217:ios:da3c0a343b17dcfe6cee80',
    messagingSenderId: '41303225217',
    projectId: 'mylez-opacity-app',
    storageBucket: 'mylez-opacity-app.appspot.com',
    iosBundleId: 'com.example.opacity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHiXkmwahk75GuRDyezUUDbG_HkuzzgfU',
    appId: '1:41303225217:ios:b55b3c3df0a0ed7d6cee80',
    messagingSenderId: '41303225217',
    projectId: 'mylez-opacity-app',
    storageBucket: 'mylez-opacity-app.appspot.com',
    iosBundleId: 'com.example.opacity.RunnerTests',
  );
}
